[build]
  functions = "functions"
  publish = "public"
[template.environment]
  FAUNA_SECRET_KEY = "FaunaDB secret key here"
  TELEGRAM_BOT_TOKEN = "Telegram bot token here"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
